# Nom de l'application
spring.application.name=secure-email-analyzer

# Port du serveur
server.port=8080

# Désactiver le warning JPA open-in-view
spring.jpa.open-in-view=false

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
logging.level.org.springframework.security=DEBUG
